<div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
  <?php foreach([['Contas',$stats['accounts']],['Analíticas',$stats['analytical']],['Categorias ativas',$stats['enabled_categories']],['De-para pendente',$stats['pending_legacy']],['Partidas',$stats['entries']],['Histórico não migrado',$stats['unposted_titles']]] as [$label,$value]):?><div class="card p-4"><div class="text-xs text-slate-500"><?=e($label)?></div><div class="mt-1 text-2xl font-bold"><?=e($value)?></div></div><?php endforeach;?>
</div>

<div class="my-5 grid gap-4 lg:grid-cols-2">
  <div class="card p-5"><h2 class="font-semibold">Configuração da empresa</h2><p class="mt-2 text-sm text-slate-600 dark:text-slate-300">Regime: <strong><?=e(str_replace('_',' ',$settings['tax_regime']))?></strong> · início contábil: <strong><?=e($settings['accounting_start_date']?br_date($settings['accounting_start_date']):'não definido')?></strong></p><a class="mt-3 inline-flex text-sm font-semibold text-teal-600" href="<?=url('settings')?>">Configurar empresa →</a></div>
  <div class="card p-5"><h2 class="font-semibold">Consistência</h2><p class="mt-2 text-sm <?=$unbalanced?'text-red-600':'text-emerald-600'?>"><?=$unbalanced?e($unbalanced).' lançamento(s) desbalanceado(s).':'Todas as partidas registradas estão balanceadas.'?></p><p class="mt-1 text-xs text-slate-500">Títulos históricos permanecem fora do razão até conciliação e saldos iniciais aprovados.</p></div>
</div>

<div class="mb-5 flex flex-wrap gap-2"><a class="btn btn-light" href="#contas">Contas</a><a class="btn btn-light" href="#categorias">Categorias</a><a class="btn btn-light" href="#legado">Migração legada</a><a class="btn btn-light" href="#templates">Modelos</a></div>

<section id="contas" class="card mb-6 overflow-hidden"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="font-semibold">Plano de contas mestre</h2><p class="text-sm text-slate-500">Contas sintéticas organizam a hierarquia; somente analíticas recebem partidas.</p></div><form class="flex gap-2"><input type="hidden" name="route" value="accounting"><input class="field" name="q" value="<?=e($q)?>" placeholder="Código ou nome"><button class="btn btn-light">Buscar</button></form></div></div><div class="table-wrap max-h-[680px]"><table class="data-table"><thead class="sticky top-0 bg-white dark:bg-slate-900"><tr><th>Código</th><th>Conta</th><th>Tipo</th><th>Natureza</th><th>Relatório</th><th>Status</th><th>Ação</th></tr></thead><tbody><?php foreach($accounts as $a):?><tr><td class="font-mono text-xs"><?=e($a['code'])?></td><td style="padding-left:<?=12+max(0,(int)$a['level']-1)*16?>px"><div class="font-medium"><?=e($a['name'])?></div><div class="text-xs text-slate-500"><?=e($a['tax_regime'])?></div></td><td><?=e(ucfirst(strtolower($a['account_type'])))?></td><td><?=$a['normal_side']==='D'?'Devedora':'Credora'?><?=$a['contra_account']?' · Redutora':''?></td><td class="text-xs"><?=e($a['report_line']?:'—')?></td><td><span class="rounded-full px-2 py-1 text-xs <?=$a['active']?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500'?>"><?=$a['active']?'Ativa':'Inativa'?></span></td><td><form method="post" action="<?=url('accounting/toggle-account')?>"><?=csrf_field()?><input type="hidden" name="account_id" value="<?=e($a['account_id'])?>"><input type="hidden" name="field" value="active"><button class="text-xs font-semibold text-teal-600"><?=$a['active']?'Desativar':'Ativar'?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="categorias" class="card mb-6 p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">Categorias financeiras e contábeis</h2><p class="text-sm text-slate-500">A categoria simplifica o lançamento e define conta contábil, controle e classe da DFC.</p></div><a class="btn btn-primary" href="<?=url('categories')?>">Gerenciar categorias</a></div></section>

<section id="legado" class="card mb-6 overflow-hidden"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold">De-para das 55 contas legadas</h2><p class="text-sm text-slate-500">A aprovação registra somente o cadastro. Saldos e movimentações não são importados.</p></div><form method="post" action="<?=url('accounting/review-legacy')?>" class="grid gap-3 border-b border-slate-200 p-5 dark:border-slate-800 md:grid-cols-3"><?=csrf_field()?><label><span class="label">Conta legada pendente</span><select class="field" name="mapping_id" required><option value="">Selecione</option><?php foreach($legacy as $l):if($l['automatic_import']||$l['review_status']!=='PENDENTE')continue;?><option value="<?=$l['id']?>"><?=e($l['legacy_code'].' · '.$l['legacy_name'])?></option><?php endif;?></select></label><label><span class="label">Conta analítica aprovada</span><select class="field" name="account_id" required><option value="">Selecione</option><?php foreach($postingAccounts as $a):?><option value="<?=e($a['account_id'])?>"><?=e($a['code'].' · '.$a['name'])?></option><?php endforeach;?></select></label><label><span class="label">Categoria financeira</span><select class="field" name="financial_category_id" required><option value="">Selecione</option><?php foreach($financialCategories as $f):?><option value="<?=e($f['category_id'])?>"><?=e($f['name'])?></option><?php endforeach;?></select></label><div class="md:col-span-3"><button class="btn btn-primary">Aprovar de-para manual</button></div></form><div class="table-wrap max-h-[520px]"><table class="data-table"><thead><tr><th>Legado</th><th>Status original</th><th>Destino</th><th>Categoria financeira</th><th>Revisão</th></tr></thead><tbody><?php foreach($legacy as $l):?><tr><td><div class="font-medium"><?=e($l['legacy_code'].' · '.$l['legacy_name'])?></div><div class="text-xs text-slate-500"><?=e($l['guidance'])?></div></td><td><?=e($l['migration_status'])?></td><td><?=e($l['target_code']?($l['target_code'].' · '.$l['target_name']):($l['candidate_accounts']?:'Sem destino automático'))?></td><td><?=e($l['financial_name']?:'—')?></td><td><span class="rounded-full px-2 py-1 text-xs <?=$l['review_status']==='APROVADO'?'bg-emerald-100 text-emerald-700':($l['review_status']==='BLOQUEADO'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700')?>"><?=e($l['review_status'])?></span></td></tr><?php endforeach;?></tbody></table></div></section>

<section id="templates" class="card overflow-hidden"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold">Modelos de partidas</h2><p class="text-sm text-slate-500">Importados como referência e mantidos desativados até parametrização operacional e revisão contábil.</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Evento/fase</th><th>Débito</th><th>Crédito</th><th>Base</th><th>Fluxo</th><th>Status</th></tr></thead><tbody><?php foreach($templates as $t):?><tr><td><div class="font-medium"><?=e($t['event_id'])?></div><div class="text-xs text-slate-500"><?=e($t['phase'])?></div></td><td><span class="font-mono text-xs"><?=e($t['debit_code'])?></span> <?=e($t['debit_name'])?></td><td><span class="font-mono text-xs"><?=e($t['credit_code'])?></span> <?=e($t['credit_name'])?></td><td><?=e($t['amount_basis'])?></td><td><?=e($t['cashflow_class'])?></td><td><span class="rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-700">Aguardando parametrização</span></td></tr><?php endforeach;?></tbody></table></div></section>
