<form class="card mb-5 flex flex-wrap items-end gap-3 p-4" method="get"><input type="hidden" name="route" value="dashboard"><label><span class="label">Período</span><select class="field" name="period" onchange="this.form.submit()"><option value="current">Mês atual</option><option value="previous" <?=($_GET['period']??'')==='previous'?'selected':''?>>Mês anterior</option><option value="custom" <?=($_GET['period']??'')==='custom'?'selected':''?>>Personalizado</option></select></label><label><span class="label">De</span><input class="field" type="date" name="start" value="<?=e($start)?>"></label><label><span class="label">Até</span><input class="field" type="date" name="end" value="<?=e($end)?>"></label><button class="btn btn-primary">Aplicar</button></form>
<section class="mb-5 grid gap-4 md:grid-cols-3">
  <div class="card bg-gradient-to-br from-teal-600 to-teal-800 p-5 text-white md:col-span-1"><p class="text-sm text-teal-100">Saldo previsto no período</p><p class="mt-2 text-3xl font-bold"><?=money((float)$totals['receivables']-(float)$totals['payables'])?></p><p class="mt-3 text-xs text-teal-100"><?=br_date($start)?> a <?=br_date($end)?></p></div>
  <div class="card p-5"><div class="flex justify-between"><p class="text-sm text-slate-500">A pagar no período</p><i class="text-red-500" data-lucide="trending-down"></i></div><p class="mt-2 text-2xl font-bold"><?=money($totals['payables'])?></p></div>
  <div class="card p-5"><div class="flex justify-between"><p class="text-sm text-slate-500">A receber no período</p><i class="text-emerald-500" data-lucide="trending-up"></i></div><p class="mt-2 text-2xl font-bold"><?=money($totals['receivables'])?></p></div>
</section>
<section class="mb-5 grid gap-4 xl:grid-cols-2">
<?php foreach(['payables'=>['Contas a pagar','red'],'receivables'=>['Contas a receber','emerald']] as $key=>[$label,$color]):?><div class="card p-5"><h2 class="mb-4 font-semibold"><?=$label?></h2><div class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p class="text-xs text-slate-500">Vencidas</p><p class="font-bold text-red-600"><?=money($cards[$key]['overdue'])?></p></div><div><p class="text-xs text-slate-500">Hoje</p><p class="font-bold text-amber-600"><?=money($cards[$key]['today'])?></p></div><div><p class="text-xs text-slate-500">Próx. 7 dias</p><p class="font-bold"><?=money($cards[$key]['next7'])?></p></div><div><p class="text-xs text-slate-500">Próx. 30 dias</p><p class="font-bold"><?=money($cards[$key]['next30'])?></p></div></div></div><?php endforeach;?>
</section>
<section class="mb-5 grid gap-4 xl:grid-cols-3"><div class="card p-5 xl:col-span-2"><h2 class="mb-4 font-semibold">Fluxo de caixa — 30 dias</h2><div class="h-72"><canvas id="cashChart"></canvas></div></div><div class="card p-5"><h2 class="mb-4 font-semibold">Custos por comportamento</h2><div class="h-52"><canvas id="categoryChart"></canvas></div><div class="mt-3 flex justify-around text-sm"><span>Fixos: <b><?=money($categorySummary['fixa']??0)?></b></span><span>Variáveis: <b><?=money($categorySummary['variavel']??0)?></b></span></div></div></section>
<section class="card"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-semibold">Alertas que pedem atenção</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Tipo</th><th>Descrição</th><th>Vencimento</th><th>Valor</th><th>Situação</th></tr></thead><tbody><?php foreach($alerts as $a):$badge=status_badge('pendente',$a['due_date']);?><tr><td><?=$a['kind']?></td><td class="font-medium"><?=e($a['description'])?></td><td><?=br_date($a['due_date'])?></td><td><?=money($a['amount'])?></td><td><span class="rounded-full px-2 py-1 text-xs font-semibold <?=$badge[1]?>"><?=$badge[0]?></span></td></tr><?php endforeach;?><?php if(!$alerts):?><tr><td colspan="5" class="text-center text-slate-500">Nenhum alerta no momento.</td></tr><?php endif;?></tbody></table></div></section>
<?php
$labels=array_column($cashflow,'day');$real=array_map('floatval',array_column($cashflow,'realized'));$projected=array_map('floatval',array_column($cashflow,'projected'));
$pageScripts='<script>const labels='.json_encode($labels).',real='.json_encode($real).',projected='.json_encode($projected).';new Chart(document.getElementById("cashChart"),{type:"line",data:{labels,datasets:[{label:"Realizado",data:real,borderColor:"#0d9488",backgroundColor:"#0d948822",fill:true,tension:.35},{label:"Projetado",data:projected,borderColor:"#f59e0b",borderDash:[7,5],tension:.35}]},options:{responsive:true,maintainAspectRatio:false}});new Chart(document.getElementById("categoryChart"),{type:"doughnut",data:{labels:["Fixos","Variáveis"],datasets:[{data:['.(float)($categorySummary['fixa']??0).','.(float)($categorySummary['variavel']??0).'],backgroundColor:["#0d9488","#f59e0b"]}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}}}});</script>';?>
